version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "georgguessr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-q58pt5wep82f"
s3_prefix = "georgguessr"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
