AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  georgguessr
  
  Serverless clone of geoguessr

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"


Resources:
  GuessrAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Guessr API Usage Plan
          UsagePlanName: GuessrUsagePlan
          Quota:
            Limit: 5000
            Period: DAY
          Throttle:
            BurstLimit: 30
            RateLimit: 30

  GeorgGuessrFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/backend/
      Handler: handler
      Runtime: go1.x
      Timeout: 20
      Events:
        GetRoom:
          Type: Api
          Properties:
            Path: /rooms/{roomID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetGamePos:
          Type: Api
          Properties:
            Path: /game/pos/{gameID}/{round}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetGameStats:
          Type: Api
          Properties:
            Path: /game/stats/{gameID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetGamePlayers:
          Type: Api
          Properties:
            Path: /game/players/{gameID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        Options:
          Type: Api
          Properties:
            Path: /{allEndpoints}
            Method: OPTION
            RestApiId: !Ref GuessrAPI
        GetAvailableRoom:
          Type: Api
          Properties:
            Path: /available-rooms
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        PostRoom:
          Type: Api
          Properties:
            Path: /rooms
            Method: POST
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        PostPanoID:
          Type: Api
          Properties:
            Path: /game/pano/{gameID}/{round}
            Method: POST
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        PostPlayer:
          Type: Api
          Properties:
            Path: /game/players/{gameID}/{username}
            Method: POST
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetCountries:
          Type: Api
          Properties:
            Path: /countries/{continent}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 'dynamodb:DeleteItem'
          - 'dynamodb:GetItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:UpdateItem'
          - 'dynamodb:Scan'
          Resource:
            'Fn::Join':
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':table/GeorgGuessrRooms'
        - Effect: Allow
          Action:
          - 'dynamodb:GetItem'
          Resource:
            'Fn::Join':
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':table/GeoContinents'
        - Effect: Allow
          Action:
          - 'dynamodb:QueryItem'
          - 'dynamodb:GetItem'
          - 'dynamodb:Scan'
          Resource:
            'Fn::Join':
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':table/GeoCities'
        - Effect: Allow
          Action:
          - 'dynamodb:QueryItem'
          - 'dynamodb:GetItem'
          - 'dynamodb:Scan'
          Resource:
            'Fn::Join':
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':table/GeoCountries'

  GeorgGuessrRooms:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: GeorgGuessrRooms
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH

  GeoContinents:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: GeoContinents
      AttributeDefinitions:
      - AttributeName: continent
        AttributeType: S
      KeySchema:
      - AttributeName: continent
        KeyType: HASH

  GeoCountries:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: GeoCountries
      AttributeDefinitions:
      - AttributeName: code
        AttributeType: S
      KeySchema:
      - AttributeName: code
        KeyType: HASH

  GeoCities:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: GeoCities
      AttributeDefinitions:
      - AttributeName: biggest
        AttributeType: N
      KeySchema:
      - AttributeName: biggest
        KeyType: HASH