version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "georgguessr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rywk61zradmv"
s3_prefix = "georgguessr"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
