AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  georgguessr
  
  Serverless clone of geoguessr

Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"


Resources:
  GuessrAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Guessr API Usage Plan
          UsagePlanName: GuessrUsagePlan
          Quota:
            Limit: 5000
            Period: DAY
          Throttle:
            BurstLimit: 30
            RateLimit: 30

  GuessrRoomsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/room/
      FunctionName: GuessrRoomsFunction
      Handler: handler
      Runtime: go1.x
      MemorySize: 512
      Events:
        GetRoom:
          Type: Api
          Properties:
            Path: /rooms/{roomID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetRoomExists:
          Type: Api
          Properties:
            Path: /exists/{roomID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        PostRoom:
          Type: Api
          Properties:
            Path: /rooms
            Method: POST
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        PostPanoramas:
          Type: Api
          Properties:
            Path: /panoramas
            Method: POST
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 'dynamodb:DeleteItem'
          - 'dynamodb:GetItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:UpdateItem'
          - 'dynamodb:Scan'
          Resource:
            'Fn::Join':
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':table/GeorgGuessrRooms'

  GuessrGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/game/
      FunctionName: GuessrGamesFunction
      Handler: handler
      Runtime: go1.x
      Events:
        GetGamePos:
          Type: Api
          Properties:
            Path: /game/pos/{gameID}/{round}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetGameStats:
          Type: Api
          Properties:
            Path: /game/stats/{gameID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetGamePlayers:
          Type: Api
          Properties:
            Path: /game/players/{gameID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        PostPlayer:
          Type: Api
          Properties:
            Path: /game/players/{gameID}/{username}
            Method: POST
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        PostGuess:
          Type: Api
          Properties:
            Path: /game/guess/{gameID}/{round}/{username}
            Method: POST
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetGuesses:
          Type: Api
          Properties:
            Path: /game/guesses/{gameID}/{round}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
        GetEndResults:
          Type: Api
          Properties:
            Path: /game/endresults/{gameID}
            Method: GET
            RestApiId: !Ref GuessrAPI
            Auth:
              ApiKeyRequired: true
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 'dynamodb:DeleteItem'
          - 'dynamodb:GetItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:UpdateItem'
          - 'dynamodb:Scan'
          Resource:
            'Fn::Join':
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':table/GeorgGuessrRooms'

  GeorgGuessrRooms:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: GeorgGuessrRooms
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true